/** Full experimental App Server schema digest generated by Codex CLI 0.144.3. */
export const APP_SERVER_SCHEMA_DIGEST_0_144_3 =
  '3b1af113954376a68d0d2382190f4bde6ca58c02a5c9a5cfebcd01f1747e79e7';

/** Full experimental App Server schema digest generated by Codex CLI 0.145.0-alpha.18. */
export const APP_SERVER_SCHEMA_DIGEST_0_145_0_ALPHA_18 =
  '7a5aaea66a649faae713d43313289ddd79b4883086c10875f9031a56ec00bd5c';
