import * as path from 'path';
import * as os from 'os';
import * as fs from 'fs';
import * as dotenv from 'dotenv';

export const configDir = path.join(os.homedir(), '.codex-feishu-bridge');
export const envPath = path.join(configDir, '.env');

export function initConfig() {
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
  if (!fs.existsSync(path.join(configDir, 'logs'))) {
    fs.mkdirSync(path.join(configDir, 'logs'), { recursive: true });
  }
  if (!fs.existsSync(envPath)) {
    const defaultEnv = `LARK_APP_ID=YOUR_FEISHU_APP_ID
LARK_APP_SECRET=YOUR_FEISHU_APP_SECRET
ALLOWED_APPROVERS=

# Rate limits querying interval in milliseconds (default: 300000 ms / 5 minutes)
RATE_LIMIT_QUERY_INTERVAL_MS=300000

# Path to the Codex CLI binary on macOS (using Desktop App bundled resources version)
CODEX_BIN=/Applications/Codex.app/Contents/Resources/codex

# Switch to output logs to a file instead of stdout (true/false)
LOG_TO_FILE=false
LOG_FILE_PATH=bridge.log

# Enable automatic upload of local files generated by Codex (e.g. /tmp/data.csv) to Feishu (true/false)
ENABLE_AUTO_FILE_UPLOAD=false
`;
    fs.writeFileSync(envPath, defaultEnv, 'utf8');
    console.log(`Created default .env config file at: ${envPath}`);
  }

  // Load environment variables
  dotenv.config({ path: envPath });
}

// Initialize config immediately on import
initConfig();

export const SESSIONS_FILE = path.join(configDir, 'sessions.json');
export const APPROVALS_FILE = path.join(configDir, 'approvals.json');
export const PUSHED_TURNS_FILE = path.join(configDir, 'pushed_turns.json');
export const APPROVAL_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
export const RATE_LIMIT_QUERY_INTERVAL_MS = parseInt(process.env.RATE_LIMIT_QUERY_INTERVAL_MS || '300000', 10);
export const LOG_DIR = path.join(configDir, 'logs');
